baseurl = "http://ivahaev.ru/"
languageCode = "ru-RU"
title = "ivahaev.ru"
copyright = "2016 Евгений Иваха"
disqusShortname = "ivahaev"

theme = "ivahaev.ru"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true
MetaDataFormat = "toml"
paginate = 10

[indexes]
    category = "categories"
    tag = "tags"
[author]
    name = "ivahaev"

[params]
    date_format = "2006-01-02"